#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# so all binaries are visible in dmenu_run
export PATH="$PATH:$HOME/dotfiles/i3-config/bin:$HOME/.bin:$HOME/bin"

# logging in with dock
# lsusb | grep -q "ThinkPad Mini Dock"
# [ "$?" -eq 0 ] && $HOME/.i3/dockery.sh dock &

# use xresources
xrdb -merge ~/dotfiles/i3-config/xresources

# multiple screen setup
#[ -e ~/.screen_setup ] && source ~/.screen_setup

# background
# [ -e ~/.fehbg ] && source ~/.fehbg
feh --bg-tile ~/.fehbg.png

# hide mouse coursor when it isn't used
unclutter &

# pulse audio session
# start-pulseaudio-x11

# keyboard layout
xmodmap ~/dotfiles/i3-config/xmodmap
[ -e ~/.xmodmap_local ] && xmodmap ~/.xmodmap_local

# color temperature adjustment, set for Gdańsk
redshift-gtk &

# notification
dunst -config ~/dotfiles/i3-config/dunstrc &

# disks automounting
udiskie &

# terminal server
# urxvtd &

# dropbox
# [ -e /usr/bin/dropboxd ] && /usr/bin/dropboxd &

# gpg agent
# export SSH_AUTH_SOCK="${HOME}/.gnupg/S.gpg-agent.ssh"
# gpg-connect-agent updatestartuptty /bye

# composition manager
compton --config ~/dotfiles/i3-config/compton.conf &

# Network Manager applet
nm-applet &
# >> /dev/null which nm-applet && nm-applet &
# >> /dev/null which blueman--applet && blueman-applet &

# caps to esc and ctrl
setxkbmap -option ctrl:nocaps
xcape -e 'Control_L=Escape'

# alt-shift keyboard layout
setxkbmap -layout us,dk -option grp:alt_shift_toggle

insync start

i3

true
