# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/martin/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

alias pau='pacaur -Syu'
alias pas='pacaur -S'
alias par='pacaur -Rs'
alias -g G='| grep -i'

eval "$(fasd --init auto)"
